name: GPT Commits summarizer
# Summary: This action will write a comment about every commit in a pull request, containing major points
# Add a comment

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  summarize:
    runs-on: ubuntu-latest

    steps:
      - uses: issc29/gpt-commit-summarizer@poolside2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          POOLSIDE_KEY: ${{ secrets.POOLSIDE_KEY }}
