name: GPT Commits summarizer
# Summary: This action will write a comment about every commit in a pull request, as well as generate a summary for every file that was modified and add it to the review page, compile a PR summary from all commit summaries and file diff summaries, and delete outdated code review comments

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  summarize:
    runs-on: ubuntu-latest
    permissions: write-all  # Some repositories need this line

    steps:
      - uses: issc29/gpt-commit-summarizer@poolside2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          POOLSIDE_KEY: ${{ secrets.POOLSIDE_KEY }}
